version: '3'
services:
  pg:
    container_name: aio-postgres
    image: postgres
    ports:
      - '5433:5432'
    expose:
      - 5433
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data